# Generated by Django 5.0.7 on 2025-09-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('vendor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('debit', 'Débito'), ('credit', 'Crédito'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, verbose_name='Medio de pago')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='Código/Obra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/originals/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.expense')),
            ],
        ),
    ]
