# Generated by Django 5.0.7 on 2025-09-19 19:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_project_alter_expense_options_expense_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='cost_type',
            field=models.CharField(choices=[('JOB', 'Job cost'), ('EQ', 'Equipment cost')], db_index=True, default='JOB', max_length=10, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='expense',
            name='subaccount',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Subaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit', 'Debit'), ('credit', 'Credit'), ('transfer', 'Transfer'), ('check', 'Check'), ('other', 'Other')], max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.project', verbose_name='Job/Project'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Job/EQ#'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(max_length=200, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Job name'),
        ),
    ]
